<a href="https://colab.research.google.com/github/Pratik-554/Deep-learning-with-TensorFlow2/blob/main/Einsum_Operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2, 6, 5, 2],
              [2,-2, 2, 3],
              [1, 5, 4, 0]])

B = np.array([[2, 9, 0, 3, 0],
              [3, 6, 8,-2, 2],
              [1, 3, 5, 0, 1],
              [3, 0, 2, 0, 5]])
print(A.shape)
print(B.shape)

print("Matmul C=: \n")
print(np.matmul(A,B), "\n")

print("Einsum C=: \n")
print(np.einsum("ij,jk -> ik", A,B))

(3, 4)
(4, 5)
Matmul C=: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 

Einsum C=: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [ ]:
A = np.array([[2, 6, 5, 2],
              [2, -2, 2,3],
              [1, 5, 4, 0]])
B = np.array([[2, 9, 0, 3],
              [3, 6, 8,-2],
              [1, 3, 5, 0]])
print(A.shape, B.shape)

print("Hardamond C=: \n")
print(A*B, "\n")

print("Einsum C=: \n")
print(np.einsum('ij,ij ->ij', A,B))

(3, 4) (3, 4)
Hardamond C=: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

Einsum C=: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [ ]:
A = np.array([[2, 6, 5, 2],
              [2,-2, 2, 3],
              [1, 5, 4, 0]])

print("Transposed A=: \n")
print(A.T, "\n")

print("Einsum Transpose A= \n")
print(np.einsum("ij -> ji", A))

Transposed A=: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]] 

Einsum Transpose A= 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [ ]:
A = np.array([
               [[2, 6, 5, 2],
                [2,-2, 2, 3],
                [1, 5, 4, 0]],

               [[1, 3, 1, 27],
                [0, 2, 2, 0],
                [1, 5, 4, 1]] ])

B = np.array([
               [[2, 9, 0, 3, 0],
                [3, 6, 8,-2, 2],
                [1, 3, 5, 0, 1],
                [3, 0, 2, 0, 5]],

               [[1, 0, 0, 3, 0],
                [3, 0, 4, -2, 2],
                [1, 0, 2, 0, 0],
                [3, 0, 1, 1, 0]] ])

print(A.shape, B.shape)

print("Batch Multiplication C =: \n")
print(np.matmul(A,B), "\n")

print("Einsum C =: \n")
print(np.einsum('bij,bjk -> bik', A,B))

(2, 3, 4) (2, 4, 5)
Batch Multiplication C =: 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[92  0 41 24  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 

Einsum C =: 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[92  0 41 24  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [ ]:
A = np.array([
               [[2, 6, 5, 2],
                [2,-2, 2, 3],
                [1, 5, 4, 0]],

               [[1, 3, 1, 27],
                [0, 2, 2, 0],
                [1, 5, 4, 1]] ])

print("Sum A =: \n")
print(np.sum(A), "\n")

print("Einsum A =: \n")
print(np.einsum('bij -> ', A))

Sum A =: 

77 

Einsum A =: 

77


In [ ]:
# Inspired from "Attention is all you need" paper
Q = batchsize, s_q, modelsize
K = batchsize, s_k, modelsize

In [ ]:
Q = np.random.randn(32, 64, 512)
K = np.random.randn(32, 128, 512)

In [ ]:
np.einsum("bqm, bkm -> bqk", Q,K).shape

(32, 64, 128)

In [ ]:
# Inspired from "Attention: The Efficient Transformer" paper
A = np.random.randn(2, 4, 4, 2) # bcij
B = np.random.randn(2, 4, 4, 1) # bcik

In [ ]:
np.einsum("bcik,bcij -> bckj", B, A).shape

(2, 4, 1, 2)

In [ ]:
np.matmul(np.transpose(B, (0,1,3,2)), A).shape

(2, 4, 1, 2)