<a href="https://colab.research.google.com/github/Pratik-554/Deep-learning-with-TensorFlow2/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tensor_zero_d = tf.constant(1)
print(tensor_zero_d)

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([3,0,3], dtype = tf.float32)
print(tensor_one_d)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.uint16)
print(casted_tensor_one_d)

tf.Tensor([3. 0. 3.], shape=(3,), dtype=float32)
tf.Tensor([3 0 3], shape=(3,), dtype=uint16)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])

print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
                            [[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_four_d = tf.constant([[[[1,2,0],
                              [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]],


                            [[[0,2,5],
                              [5,3,1]],

                            [[0,2,0],
                             [-1,10,0]],

                            [[0,5,1],
                             [1,7,0]],

                            [[3,8,7],
                             [-1,7,0]]],


                            [[[4,5,4],
                              [3,1,1]],

                            [[0,2,5],
                             [0,4,3]],

                            [[3,2,4],
                             [5,8,3]],

                            [[8,2,5],
                             [2,3,3]]]])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 0  2  5]
   [ 5  3  1]]

  [[ 0  2  0]
   [-1 10  0]]

  [[ 0  5  1]
   [ 1  7  0]]

  [[ 3  8  7]
   [-1  7  0]]]


 [[[ 4  5  4]
   [ 3  1  1]]

  [[ 0  2  5]
   [ 0  4  3]]

  [[ 3  2  4]
   [ 5  8  3]]

  [[ 8  2  5]
   [ 2  3  3]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
x = tf.constant(1, shape=(4,4))
print(x)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(4, 4), dtype=int32)


In [ ]:
x_np = np.array([3,4,5])
print(x_np)

[3 4 5]


In [ ]:
x_tf = tf.convert_to_tensor(x_np, dtype = tf.float16)
print(x_tf)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float16)


In [ ]:
identity_matrix = tf.eye(4,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print(identity_matrix)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)


In [ ]:
filled_tensor = tf.fill([4,3], 19)
print(filled_tensor)

tf.Tensor(
[[19 19 19]
 [19 19 19]
 [19 19 19]
 [19 19 19]], shape=(4, 3), dtype=int32)


In [ ]:
ones_tensor = tf.ones([4,3], dtype = tf.float32)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [ ]:
zeros_tensor = tf.zeros([4,3], dtype = tf.float32)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(tensor_four_d)
print(ones_like_tensor)
print(tensor_four_d.shape)

tf.Tensor(
[[[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]], shape=(3, 4, 2, 3), dtype=int32)
(3, 4, 2, 3)


In [ ]:
normal_tensor = tf.random_normal_initializer(
    mean=0.0, stddev=0.05, seed=None
)

In [ ]:
print(normal_tensor)

In [ ]:
range_tensor = tf.range(start = 2, limit = 10, delta = 3)
print(range_tensor)

tf.Tensor([2 5 8], shape=(3,), dtype=int32)


In [ ]:
print(tf.shape(tensor_three_d))
print(tensor_three_d.shape)

tf.Tensor([4 2 3], shape=(3,), dtype=int32)
(4, 2, 3)


In [ ]:
print(tf.size(tensor_four_d))

tf.Tensor(72, shape=(), dtype=int32)


In [ ]:
g = tf.random.Generator.from_non_deterministic_state()
g.normal(shape=(2,), mean = 100, stddev = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([101.583534, 100.3688  ], dtype=float32)>

In [ ]:
g = tf.random.Generator.from_non_deterministic_state()
g.uniform(shape=(2,), minval = 25, maxval = 40)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([28.469366, 27.89954 ], dtype=float32)>

In [ ]:
tf.random.normal(
    (3,),
    mean=0.0,
    stddev=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name="Random number with Normal distribution"
)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 120.40747 ,   20.313623, -101.69369 ], dtype=float32)>

In [ ]:
tf.random.uniform(
    (2,),
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([76.19617, 67.06528], dtype=float32)>

In [ ]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:5+1])
print(tensor_indexed[3:-3])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])

#print(tensor_two_d[0:3, :])
print(tensor_two_d[...,1])

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
                            [[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]])
#print(tensor_three_d[0, : , :])
#print(tensor_three_d[0:2, :, 2])
print(tensor_three_d[... , : , 2])

tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


In [ ]:
# real number
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
tf.abs(tf.constant([-0.2]))

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.2], dtype=float32)>

In [ ]:
# complex number
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)  # For a complex number a+bj, its absolute value is computed as square root(a^2+b^2)


<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [ ]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [38]:
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.int32)
x_2 = tf.constant([7], dtype = tf.int32)

#print(tf.math.divide(x_1, x_2))
print(tf.math.add(x_1, x_2))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [41]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32) # both x_1 & x_2 should have 1 to stretch other dimensionin in order to make same
print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [47]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])
print(x_argmax.shape)
print(tf.math.argmin(x_argmax, axis = 1)) # Returns the index with the largest(for argmax) value across hor. axes for axis=1 of a tensor.

(3, 5)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [46]:
x_argmax = tf.constant([200, 120, 130, 3, 6])
# print(tf.math.argmax(x_argmax))
print(tf.math.argmin(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [45]:
x_argmax = tf.constant([200, 120, 130, 300, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [49]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [50]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [63]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)

print(tensor_two_d.shape)

#print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=False, name=None))  # axis = 0 represents columns
#print(tf.math.reduce_mean(tensor_two_d, axis=0, keepdims=False, name=None))
print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True, name=None))  # 	keepdims = true, retains reduced dimensions with length 1

#print(tf.math.reduce_max(tensor_two_d, axis=None, keepdims=False, name=None))
#print(tf.math.reduce_min(tensor_two_d, axis=None, keepdims=False, name=None))

(4, 3)
tf.Tensor([[ 0.829  2.861 41.38 ]], shape=(1, 3), dtype=float16)


In [66]:
tf.math.top_k(tensor_two_d, k=2)  # by default k=1

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[  1.,   0.],
       [100.,   5.],
       [  6.,   5.],
       [  8.,   3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)